### ISSUE TITLE
Logo/koszulka

### ISSUE THREAD

**Issue by Agata91** [Agata91/Projekt#1]
poproszę logo :)

**Comment by igortnt** [comment]
![koszulka 2](https://cloud.githubusercontent.com/assets/9257004/5633291/123ba916-95d6-11e4-9e88-c953318bd2fc.jpg)
 Otworzyłem temat aby zaproponować dodatkowy model koszulki zespołu :) Bardzo spodobał mi się pomysł plakatu od Agaty i stwierdziłem, że idealnie wpasuje się na koszulkę :D Co sądzicie?
