### ISSUE TITLE
Bilet koncertowy 

### ISSUE THREAD

**Issue by Agata91** [Agata91/Projekt#4]
![ticket-killaside](https://cloud.githubusercontent.com/assets/9256934/5616551/d024b386-9505-11e4-865d-d3b6ea34609d.png)

**Comment by Agata91** [comment]
zmieniłam rok na 2016:)

**Comment by igortnt** [comment]
Kawał dobrej roboty! :D Bilet jak się patrzy :) Pasuje do stylistyki!

**Comment by Agata91** [comment]
![ticket-killaside1](https://cloud.githubusercontent.com/assets/9256934/5651601/0dd499f4-96a9-11e4-95b6-426fdc919acd.png)

Propozycja druga, myślę,że lepsza :)

**Comment by sebek1030** [comment]
obie wersje świetne ;)
