### ISSUE TITLE
Ulotka koncertowa

### ISSUE THREAD

**Issue by Agata91** [Agata91/Projekt#6]
![ulotka](https://cloud.githubusercontent.com/assets/9256934/5651933/43e95b30-96ac-11e4-826c-a8fa1be9fb11.png)
Hmm?

**Comment by Agata91** [comment]
ohh mała poprawka (odstępy w roku)
![ulotka](https://cloud.githubusercontent.com/assets/9256934/5651961/8a98b9f4-96ac-11e4-9305-df4b8b40f91d.png)
Co zmienić mili Panowie?:D

**Comment by sebek1030** [comment]
absolutnie nic nie zmieniaj :P

**Comment by igortnt** [comment]
Jest świetnie! :)
