### ISSUE TITLE
Wizytówka

### ISSUE THREAD

**Issue by sebek1030** [Agata91/Projekt#7]
Oto propozycja wizytowki 
![wizytowka](https://cloud.githubusercontent.com/assets/9265555/5653116/9ae02990-96b7-11e4-8f48-d149f15f1bda.jpg)

**Comment by igortnt** [comment]
No i dobrze Sebku :)

**Comment by sebek1030** [comment]
malutkie zmiany 
![wizytowka2](https://cloud.githubusercontent.com/assets/9265555/5746580/da7a16c8-9c30-11e4-81c5-46afa794d4dd.jpg)
